-- SINGLE RAW FUNCTION
--WILL AFFECT EACH AND EVERY RAW AND RETURN SAME NUMBER OF RAWS
--

SELECT UPPER(FIRST_NAME) , LOWER(LAST_NAME), 
SUBSTR (FIRST_NAME,1,1) || SUBSTR (LAST_NAME,1,1)
AS INITIALS FROM EMPLOYEES;

-- FIND EMPLOYEES THAT CONTAINS MI IN THEIR NAME(FIRST NAME OR LAST NAME),CASE INSENSETIVE

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE '%MI%' OR UPPER(LAST_NAME) LIKE '%MI%' ;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '%mi%' OR LOWER (LAST_NAME) LIKE '%mi%';
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '%mi%' OR UPPER(LAST_NAME) LIKE '%MI%' ;

--  123456789
--  21-MAY-07
-- SUBSTR (VALUE, STARTING INDEX, CHARACTER COUNT YOU WANT TO GET!)

select hire_date, substr(hire_date,4,3) from employees; -- 3 IS FOR THREE CHARACTERS OF MONTH

-- BY EXTENDING ABOVE QUERY, FIND OUT EVERYONE WHO WAS HIRED IN JAN
select first_name, hire_date from employees where substr(hire_date,4,3) = 'JAN' ;



